name: "CI Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-l12-stable:
    runs-on: ubuntu-latest
    name: P8.4 - L12 - prefer-stable - ubuntu
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      - run: composer require "laravel/framework:12.*" "orchestra/testbench:10.*" "nesbot/carbon:3.*" --no-interaction --no-update
      - run: composer update --prefer-stable --prefer-dist --no-interaction
      - run: vendor/bin/pest --ci

  test-l12-lowest:
    runs-on: ubuntu-latest
    name: P8.4 - L12 - prefer-lowest - ubuntu
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      - run: composer require "laravel/framework:12.*" "orchestra/testbench:10.*" "nesbot/carbon:3.*" --no-interaction --no-update
      - run: composer update --prefer-lowest --prefer-dist --no-interaction
      - run: vendor/bin/pest --ci

  test-l13-stable:
    runs-on: ubuntu-latest
    name: P8.5 - L13 - prefer-stable - ubuntu
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      - run: composer require "laravel/framework:13.*" "orchestra/testbench:11.*" "nesbot/carbon:3.*" --no-interaction --no-update
      - run: composer update --prefer-stable --prefer-dist --no-interaction
      - run: vendor/bin/pest --ci